export const sliderMovieData = [
  {
    id: "tt6718170",
    title: "The Super Mario Bros. Movie",
    fullTitle: "The Super Mario Bros. Movie (2023)",
    year: "2023",
    releaseState: "05 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BOTJhNzlmNzctNTU5Yy00N2YwLThhMjQtZDM0YjEzN2Y0ZjNhXkEyXkFqcGdeQXVyMTEwMTQ4MzU5._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "92",
    runtimeStr: "92 mins",
    plot: "The story of The Super Mario Bros. on their journey through the Mushroom Kingdom.",
    contentRating: "PG",
    imDbRating: "7.4",
    imDbRatingCount: "37027",
    metacriticRating: "46",
    genres: "Animation, Adventure, Comedy",
    directors: "Aaron Horvath, Michael Jelenic, Pierre Leduc, Fabien Polack",
    stars: "Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black",
  },
  {
    id: "tt2906216",
    title: "Dungeons & Dragons: Honor Among Thieves",
    fullTitle: "Dungeons & Dragons: Honor Among Thieves (2023)",
    year: "2023",
    releaseState: "31 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BZjAyMGMwYTEtNDk4ZS00YmY0LThhZjUtOWI4ZjFmZmU4N2I3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0._V1_Ratio0.6794_AL_.jpg",
    runtimeMins: "134",
    runtimeStr: "134 mins",
    plot: "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.",
    contentRating: "PG-13",
    imDbRating: "7.6",
    imDbRatingCount: "35617",
    metacriticRating: "72",
    genres: "Action, Adventure, Comedy",
    directors: "John Francis Daley, Jonathan Goldstein",
    stars: "Chris Pine, Michelle Rodriguez, Regé-Jean Page, Justice Smith",
  },
  {
    id: "tt10366206",
    title: "John Wick: Chapter 4",
    fullTitle: "John Wick: Chapter 4 (2023)",
    year: "2023",
    releaseState: "24 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "169",
    runtimeStr: "169 mins",
    plot: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    contentRating: "R",
    imDbRating: "8.3",
    imDbRatingCount: "106257",
    metacriticRating: "78",
    genres: "Action, Crime, Thriller",
    directors: "Chad Stahelski",
    stars: "Keanu Reeves, Laurence Fishburne, George Georgiou, Lance Reddick",
  },
  {
    id: "tt16419074",
    title: "Air",
    fullTitle: "Air (2023)",
    year: "2023",
    releaseState: "05 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYmNlOTNlYjUtM2U3Yy00M2ZjLTkxZDQtN2NiNGZiZDI0ZjE3XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "111",
    runtimeStr: "111 mins",
    plot: "Follows the history of shoe salesman Sonny Vaccaro, and how he led Nike in its pursuit of the greatest athlete in the history of basketball, Michael Jordan.",
    contentRating: "R",
    imDbRating: "7.8",
    imDbRatingCount: "10332",
    metacriticRating: "73",
    genres: "Drama, Sport",
    directors: "Ben Affleck",
    stars: "Matt Damon, Jason Bateman, Ben Affleck, Chris Messina",
  },
  {
    id: "tt1630029",
    title: "Avatar: The Way of Water",
    fullTitle: "Avatar: The Way of Water (2022)",
    year: "2022",
    releaseState: "16 Dec 2022",
    image:
      "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_Ratio0.6986_AL_.jpg",
    runtimeMins: "192",
    runtimeStr: "192 mins",
    plot: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    contentRating: "PG-13",
    imDbRating: "7.7",
    imDbRatingCount: "349790",
    metacriticRating: "67",
    genres: "Action, Adventure, Fantasy",
    directors: "James Cameron",
    stars: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
  },
  {
    id: "tt11145118",
    title: "Creed III",
    fullTitle: "Creed III (2023)",
    year: "2023",
    releaseState: "03 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYWY1ZDY4MmQtYjhiYS00N2QwLTk1NzgtOWI2YzUwZThjNDYwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "116",
    runtimeStr: "116 mins",
    plot: "Adonis has been thriving in both his career and family life, but when a childhood friend and former boxing prodigy resurfaces, the face-off is more than just a fight.",
    contentRating: "PG-13",
    imDbRating: "7",
    imDbRatingCount: "43584",
    metacriticRating: "73",
    genres: "Drama, Sport",
    directors: "Michael B. Jordan",
    stars: "Michael B. Jordan, Tessa Thompson, Jonathan Majors, Wood Harris",
  },
  {
    id: "tt10151854",
    title: "Shazam! Fury of the Gods",
    fullTitle: "Shazam! Fury of the Gods (2023)",
    year: "2023",
    releaseState: "17 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BNzJlM2NmZTItOGQyYS00MmE2LTkwZGUtNDFkNmJmZjRjZjcxXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "130",
    runtimeStr: "130 mins",
    plot: 'The film continues the story of teenage Billy Batson who, upon reciting the magic word "SHAZAM!" is transformed into his adult Super Hero alter ego, Shazam.',
    contentRating: "PG-13",
    imDbRating: "6.2",
    imDbRatingCount: "41450",
    metacriticRating: "47",
    genres: "Action, Adventure, Comedy",
    directors: "David F. Sandberg",
    stars: "Zachary Levi, Asher Angel, Jack Dylan Grazer, Rachel Zegler",
  },
];

export const sliderDateData = [
  {
    date: 1,
    year: 2023,
    month: "August",
    fullDateInfo: 1,
  },
  {
    date: 2,
    year: 3,
    month: "August",
    fullDateInfo: 12,
  },
  {
    date: 3,
    year: 2023,
    month: "August",
    fullDateInfo: 123,
  },
  {
    date: 4,
    year: 2023,
    month: "August",
    fullDateInfo: 1234,
  },
  {
    date: 5,
    year: 2023,
    month: "August",
    fullDateInfo: 12345,
  },
  {
    date: 6,
    year: 2023,
    month: "August",
    fullDateInfo: 123456,
  },
  {
    date: 7,
    year: 2023,
    month: "August",
    fullDateInfo: 1234567,
  },
];
