export enum TypographyVariant {
  poppins_r = "poppins_r",
  poppins_sb = "poppins_sb",
  poppins_m = "poppins_m",
  poppins_b = "poppins_b",
  poppins_l = "poppins_l",
  nunito_l = "nunito_l",
  nunito_l_ital = "nunito_l_ital",
  nunito_r = "nunito_r",
  nunito_b = "nunito_b",
  inter_sb = "inter_sb",
  inter_b = "inter_b",
  inter_r = "inter_r",
  inria_l_ital = "inria_l_ital",
}
